CREATE TABLE IF NOT EXISTS "self_prospecting_leads" (
	"id" serial PRIMARY KEY NOT NULL,
	"source_url" text NOT NULL,
	"source_platform" text,
	"subreddit" text,
	"author" text,
	"post_excerpt" text,
	"post_full_text" text,
	"posted_at" timestamp with time zone,
	"intent_score" integer DEFAULT 0 NOT NULL,
	"intent_tier" text,
	"specificity" integer DEFAULT 0 NOT NULL,
	"location_match" integer DEFAULT 0 NOT NULL,
	"recency" integer DEFAULT 0 NOT NULL,
	"budget_signals" integer DEFAULT 0 NOT NULL,
	"total_score" integer DEFAULT 0 NOT NULL,
	"matched_keywords" jsonb DEFAULT '[]',
	"drafted_message" text,
	"no_mention_mode" boolean DEFAULT false,
	"subreddit_note" text,
	"status" text DEFAULT 'new' NOT NULL,
	"notes" text,
	"contractor_slug" text,
	"contractor_name" text,
	"conversion_value_monthly" integer,
	"found_at" timestamp with time zone DEFAULT now(),
	"sent_at" timestamp with time zone,
	"replied_at" timestamp with time zone,
	"converted_at" timestamp with time zone,
	"discarded_at" timestamp with time zone,
	CONSTRAINT "self_prospecting_leads_source_url_unique" UNIQUE("source_url")
);
